Captain_console/Captain_console/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('store/', include('store.urls')),
    path('login/', include('login.urls')),
    path('shoppingcart/', include('shoppingcart.urls')),
    path('checkout/', include('checkout.urls')),
    path('account/', include('account.urls')),
]

Captain_console/checkout/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="checkout_index"),
    path('<int:id>', views.index, name="checkout_index"),

    path('contactinfo/', views.index, name="checkout_index"),
    path('contactinfo', views.index, name="checkout_index"),
    path('contactinfo/<int:id>', views.index, name="checkout_index"),

    path('shipping/', views.shipping, name="checkout_shipping"),
    path('shipping', views.shipping, name="checkout_shipping"),
    path('shipping/<int:id>', views.shipping, name="checkout_shipping"),

    path('payment/', views.payment, name="checkout_payment"),
    path('payment', views.payment, name="checkout_payment"),
    path('payment/<int:id>', views.payment, name="checkout_payment"),

    path('confirmation/', views.confirmation, name="checkout_confirmation"),
    path('confirmation', views.confirmation, name="checkout_confirmation"),
    path('confirmation/<int:id>', views.confirmation, name="checkout_confirmation"),
]

Captain_console/home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="home_index"),
    path('<int:id>', views.index_logout, name="home_index_logout")
]

Captain_console/shoppingcart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="shoppingcart_index")
]

Captain_console/account/models.py
from django.db import models


class User(models.Model):
    username = models.CharField(max_length=64)
    password = models.CharField(max_length=512)
    email = models.CharField(max_length=128)

    def __str__(self):
        return self.username

    @staticmethod
    def insert(username, email, password):
        User.objects.create(username=username, email=email, password=password)

    """
        Checks if email already exists in the database
        Returns True if email exists, False otherwise
    """
    @staticmethod
    def email_already_exists(email):
        data_count = User.objects.filter(email=email).count()
        if data_count == 0:
            return False
        else:
            return True

    @staticmethod
    def get_password(email):
        user_obj = User.objects.filter(email=email)
        for user in user_obj:
            return user.password
        return None


class PaymentInfo(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=128)
    exp_date = models.CharField(max_length=6)
    card_number = models.CharField(max_length=19)
    cvc = models.CharField(max_length=3, blank=True)

    @staticmethod
    def insert(user_id, name, number, exp, cvc):
        PaymentInfo.objects.create(user_id=user_id, name=name, card_number=number, exp_date=exp, cvc=cvc)


class Address(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=64)
    city = models.CharField(max_length=64)
    country = models.CharField(max_length=64)
    zip_code = models.CharField(max_length=10)

    @staticmethod
    def insert(user_id, address, city, country, zip_code):
        Address.objects.create(user_id=user_id, address=address, city=city, country=country, zip_code=zip_code)


class UserPhoto(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    path = models.CharField(max_length=200)
    alt = models.CharField(max_length=128, blank=True)

Captain_console/checkout/models.py
from django.db import models
from account.models import User
from store.models import Product


# Maybe these models can change locations but I'll leave it here for now

class OrderProduct(models.Model):
    '''Shoppingcart'''
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.FloatField()


class Order(models.Model):
    total_price = models.FloatField()
    tracking_nr = models.CharField(max_length=128)
    date = models.DateField(auto_now_add=True)
    orderproduct_id = models.ManyToManyField('OrderProduct')


#
# class OrderCart(models.Model):
#     order_id = models.ForeignKey(Order, on_delete=models.CASCADE)
#     orderproduct_id = models.ForeignKey(OrderProduct, on_delete=models.CASCADE)
#




#######################

Captain_console/shoppingcart/models.py
from django.db import models

# Create your models here.

Captain_console/store/models.py
from django.db import models
from account.models import User

class Category(models.Model):
    name = models.CharField(max_length=64)

class Product(models.Model):
    name = models.CharField(max_length=128)
    price = models.FloatField()
    discount = models.FloatField(null=True)
    copies_sold = models.IntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    average_rating = models.FloatField(null=True)


    """
    Sets average rating of a product
    """
    def set_rating(self, rating, prod_id):
        Product.objects.filter(pk=prod_id).update(average_rating="{:.2f}".format(rating))

    """
    Returns average rating of a product
    """

    def get_rating(self):
        reviews = Review.objects.filter(product_id=self.id)

        total_ratings = 0
        for review in reviews:
            total_ratings += review.rating
        avg_rating = total_ratings / len(reviews)
        return avg_rating

    def __str__(self):
        return self.name

    """
        Returns the discounted price with two decimal numbers
    """

    def get_discounted_price(self):
        return "{:.2f}".format(self.price * 0.01 * (100 - self.discount))

    """
        Returns the total discount and removes any trailing zeros from float,
        ex. '50.0 => 50', and '13.5 => 13.5'
    """

    def get_discount(self):
        return "{:g}".format(self.discount)


class Genre(models.Model):
    genre = models.CharField(max_length=128)


class Developer(models.Model):
    developer = models.CharField(max_length=128)


class ProductDetails(models.Model):
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE)
    genre_id = models.ForeignKey(Genre, on_delete=models.CASCADE)
    developer_id = models.ForeignKey(Developer, on_delete=models.CASCADE)
    release_date = models.DateField()
    description = models.TextField()


class ProductPhoto(models.Model):
    path = models.CharField(max_length=999)
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE)
    alt = models.CharField(max_length=128, blank=True)

    def __str__(self):
        return self.path


class Review(models.Model):
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.IntegerField()
    comment = models.TextField(blank=True)

    def create_review(self, prod_id, user_id, rating):
        Review.objects.create(product_id=prod_id, user_id=user_id, rating=rating, comment="")

    def __str__(self):
        return str(self.rating)

Captain_console/checkout/views.py
import json
from itertools import chain
from django.http import HttpResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt

from account.models import User, PaymentInfo
from store.models import Product
from checkout.models import Order, OrderProduct, OrderCart


def base_context(id, context):
    context['user'] = User.objects.get(pk=id)
    # context['order_products'] = Product.objects.raw('SELECT * FROM store_product, store_orderproduct, store_order WHERE store_product.id = store_orderproduct.product_id_id  AND store_orderproduct.order_id_id = store_order.id  AND store_order.user_id_id = s%;', [id])

    # print(context)
    # context['order_products'] = Product.objects.raw('SELECT * FROM store_product, store_orderproduct, store_order WHERE store_product.id = store_orderproduct.product_id_id  AND store_orderproduct.order_id_id = store_order.id  AND store_order.user_id_id = s%;', [id])

    # Þetta er vitlaust, þarf að pulla order_id úr order_product og matcha við þetta
    # Eins og er, er þetta allavega einhver data fyrir shoppingcart
    context['order_products'] = OrderProduct.objects.filter(user_id_id=id)
    p = OrderProduct.objects.filter(user_id=id)


    if len(p) > 1 :
        for order in p :
            o = Product.objects.filter(orderproduct__ordercart__order_id=)
                # pk=order.product_id)
            OrderProduct.objects.filter(user_id_id=id, order)
            p = Order.objects.filter(ordercart__orderproduct_id__user_id=1)

    # u = User.objects.get(pk=id)
    # p = Order.objects.get('user_id_id'=id)
    # d = Product.objects.all()
    # o = Order.objects.all(user_id=1)

    # o = Order.objects.filter(user_id_id=1)
    # op = OrderProduct.objects.exclude(o.order_id_id)

    return context

 # products = Product.objects.filter(orderproduct__order_id__user_id=id)


def index(request, id=None):
    print("hello")
    context = {
        'page_checkout': 'contactinfo',
        'order_products': 'order_products',
    }
    if id != None:
        context = base_context(id, context)
    return render(request, 'checkout/index.html', context)


def shipping(request, id=None):
    context = {
        'page_checkout': 'shipping',
    }
    if id != None:
        context = base_context(id, context)
    return render(request, 'checkout/index.html', context)


@csrf_exempt
def payment(request, id=None):
    if request.method == 'POST':
        # Make sure user is logged in
        if request.session.get('user_id') is None:
            response = json.dumps({'status': 999, 'message': 'User not logged in'})
            return HttpResponse(response, content_type='application/json')

        cardHolder = request.POST.get('cardHolder')
        cardNumber = request.POST.get('cardNumber')
        expireDate = request.POST.get('expireDate')
        cvc = request.POST.get('cvc')

        PaymentInfo.insert(User.objects.get(pk=request.session.get('user_id')), cardHolder, cardNumber, expireDate, cvc)

        response = json.dumps({'status': 200, 'message': 'Yes'})
        return HttpResponse(response, content_type='application/json')

    context = {
        'page_checkout': 'paymentinfo',
    }

    if id != None:
        context = base_context(id, context)
    return render(request, 'checkout/index.html', context)


def confirmation(request, id=None):
    context = {
        'page_checkout': 'confirmation',
    }
    if id != None:
        context = base_context(id, context)
    return render(request, 'checkout/index.html', context)

Captain_console/shoppingcart/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'shoppingcart/index.html')

Captain_console/templates/checkout/confirmation.html
    <a class="modal-trigger" href="#modal1"><i class="material-icons icn_profile waves-effect">person</i></a>



   <div id="modal1" class="modal">
    <div class="modal-content">
      <h4>Modal Header</h4>
      <p>A bunch of text</p>
    </div>
    <div class="modal-footer">
      <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Agree</a>
    </div>
  </div>



{##}
{#<div class="card-panel white">#}
{#    <h3 class="card-title">Confirmation</h3>#}
{#    <form class="col s12">#}
{##}
{#        <div class="row">#}
{#            <div class="input-field col s12">#}
{#                <h5>Your order has been placed</h5>#}
{#                <p>Thank you for your purchase!</p>#}
{#                <p>A confirmation email will be sent to: personpersonsson@gmail.com</p>#}
{#            </div>#}
{#        </div>#}
{##}
{#        <a class="btn waves-effect blue accent-3"  href="/store">Continue shopping#}
{#        <i class="material-icons right">shopping_cart</i></a>#}
{##}
{#    </form>#}
{#</div>#}

Captain_console/templates/checkout/contactinfo.html
<div class="card-panel white">
    <h3 class="card-title">Contact information</h3>

    <form >
        <div class="row">
            <div class="img-field col s4 offset4">
                <img class="circle responsive-img"  src="{{user.userphoto_set.first.path}}" alt="{{ user.userphoto_set.first.alt }}"/>
            </div>
        </div>

         <div class="row">
            <div class="input-field col s12">
                <i class="material-icons prefix icon-blue">account_box</i>
                <input id="contact-info" type="text" required value="{{ user.username }}">
                <label for="contact-info">Full name</label>
            </div>

            <div class="input-field col s12">
                <i class="material-icons prefix">email</i>
                <input id="email" type="email" class="validate" required value="{{ user.email }}">
                <label for="email">Email</label>
                <span class="helper-text" data-error="Please enter a valid email address"></span>
            </div>
        </div>

        <div class="row">
            <a class="btn waves-effect blue accent-3 move-buttons"  href="../">Cancel
            <i class="material-icons right">cancel</i></a>

            <a class="btn waves-effect blue accent-3 move-buttons"  href="{% if user.id %}{% url 'checkout_shipping' user.id %}{% else %}{% url 'checkout_shipping' %}{% endif %}">Next
                <i class="material-icons right">arrow_forward</i>
            </a>
        </div>
    </form>
</div>

Captain_console/templates/checkout/crumbs.html
<ul class="crumbs">
    <li {% if page_checkout == 'contactinfo' %} {{ 'class="active"' }} {% endif %}>
        <a href="{% if user.id %}{% url 'checkout_index' user.id %}{% else %}{% url 'checkout_index' %}{% endif %}">Contact Info</a></li>

    <li {% if page_checkout == 'shipping' %} {{ 'class="active"' }} {% endif %}>
        <a href="{% if user.id %}{% url 'checkout_shipping' user.id %}{% else %}{% url 'checkout_shipping' %}{% endif %}">Shipping</a></li>

    <li {% if page_checkout == 'paymentinfo' %} {{ 'class="active"' }} {% endif %}>
        <a href="{% if user.id %}{% url 'checkout_payment' user.id %}{% else %}{% url 'checkout_payment' %}{% endif %}">Payment</a></li>

</ul>

Captain_console/templates/checkout/index.html
{%  extends 'base.html' %}
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static "css/checkout.css" %}">
    <link rel="stylesheet" href="{% static "css/shared/custom-breadcrumbs.css" %}">
{% endblock %}

{% block content %}
<div class = "checkout container">
    <div class="checkout_inner container">
        {% include 'checkout/crumbs.html' %}
        <div class="col s4 m6">
            {% if page_checkout == 'contactinfo' %}
                {% include 'checkout/contactinfo.html' %}
            {% elif page_checkout == 'shipping' %}
                {% include 'checkout/shipping.html' %}
            {% elif page_checkout == 'paymentinfo' %}
                {% include 'checkout/paymentinfo.html' %}
            {% endif %}
        </div>
        <div class="col s4 m6 fix-content">
            <div class="card-panel white">
                <span class="col s12">
                    {% include 'checkout/shoppingcart.html' with order_products=order_products %}
                </span>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
    <script src="{% static "js/checkout.js" %}"></script>
    {% if page_checkout == 'paymentinfo' %}
        <script src="{% static "js/paymentinfo.js" %}"></script>
        <script src="{% static "js/checkout.js" %}"></script>
    {% endif %}
{%endblock%}

Captain_console/templates/checkout/paymentinfo.html
<div class="card-panel white">
    <h3 class="card-title">Payment information</h3>

    <div class="row">
        <div class="input-field col s12">
            <i class="material-icons prefix">account_box</i>
            <input id="card_nameholder" type="text" class="validate" required  value="{{user.paymentinfo_set.first.name}}">
            <label for="card_nameholder">Cardholder name</label>
        </div>

        <div class="input-field col s12">
            <i class="material-icons prefix">credit_card</i>
            <input id="card_number" type="tel" class="validate" required  value="{{user.paymentinfo_set.first.card_number}}">
            <label for="card_number">Card number</label>
        </div>

        <div class="input-field col s12 m6">
            <i class="material-icons prefix">date_range</i>
            <input id="exp_date" type="text" class="validate" required  value="">
            <label for="exp_date">Expire date (01/21)</label>
        </div>

        <div class="input-field col s12 m6">
            <i class="material-icons prefix">security</i>
            <input id="cvc_number" type="text" class="validate" required  value="">
            <label for="cvc_number">CVC</label>
        </div>
    </div>

    <div class="row">
        <div class="input-field col s12">
            <label>
                <input id="remember_creditcard" type="checkbox" class="checkbox-blue"/>
                <span>Do you want us to remember your card for next time?</span>
            </label>
        </div>
    </div>
    <div class="row">
        <br>
    </div>
    <div class="row">
        <a class="btn waves-effect blue accent-3 move-buttons"
           href="   {% if user.id %}
                        {% url 'checkout_shipping' user.id %}
                    {% else %}
                        {% url 'checkout_shipping' %}
                    {% endif %}">Back
        <i class="material-icons right">arrow_back</i></a>

        <a class="btn waves-effect blue accent-3 modal-trigger move-buttons" href="#modal1" id="confirm-payment">Submit
        <i class="material-icons right">arrow_forward</i></a>
    </div>
</div>

<!-- Modal Structure -->
<div id="modal1" class="modal">
    <div class="modal-content">
        <h4>Your order has been placed</h4>
            <p>Thank you for your purchase!<br>
            A confirmation email will be sent to: {{ user.email }}</p>
            </div>
            <div class="modal-footer">
        <a href="#" class=" modal-action modal-close waves-effect waves-green btn-flat">Ok</a>
    </div>
</div>

Captain_console/templates/checkout/shipping.html
<div class="card-panel white">
    <h3 class="card-title">Shipping information</h3>
    <div class="row">
        <div class="input-field col s12">
            <i class="material-icons prefix">home</i>
            <input id="icon_prefix" type="text" class="validate" required value="{{user.address_set.first.address}}">
            <label for="icon_prefix">Address</label>
        </div>

        <div class="input-field col s12">
            <i class="material-icons prefix">landscape</i>
            <input id="icon_prefix" type="tel" class="validate" required value="{{user.address_set.first.country}}">
            <label for="icon_prefix">Country</label>
        </div>

        <div class="input-field col s6">
            <i class="material-icons prefix">location_city</i>
            <input id="icon_prefix" type="text" class="validate" required value="{{user.address_set.first.city}}">
            <label for="icon_prefix">City</label>
        </div>

        <div class="input-field col s6">
            <input id="icon_prefix" type="text" class="validate" required value="{{user.address_set.first.zip_code}}">
            <label for="icon_prefix">Zip</label>
        </div>
    </div>

    <div class="row">
        <a class="btn waves-effect blue accent-3 move-buttons"  href="{% if user.id %}{% url 'checkout_index' user.id %}{% else %}{% url 'checkout_index' %}{% endif %}">Back
        <i class="material-icons right">arrow_back</i></a>

        <a class="btn waves-effect blue accent-3 move-buttons"  href="{% if user.id %}{% url 'checkout_payment' user.id %}{% else %}{% url 'checkout_payment' %}{% endif %}">Next
            <i class="material-icons right">arrow_forward</i>
        </a>
    </div>
</div>

Captain_console/templates/checkout/shoppingcart.html
<div class="row">
    <div class="input-field col s12">
        {% for order_product in order_products %}
            {% include 'checkout/shoppingcart_element.html' with order_product=order_product %}
        {% endfor %}
    </div>
</div>



<!--
    A single card that contains the product title, image, price and available discount (if any)
-->

            <div class="row">
                <img class="product-img" src="{{ product.productphoto_set.first.path}}" alt="{{ product.productphoto_set.first.alt }}">

                <div class="card-stacked">
                    <div class="card-content">
                        <span class="card-title activator grey-text text-darken-4">{{ product.name }}</span>
                            {% if product.discount <= 0 %}
                                <strong class="flow-text set-price">${{ product.price }}</strong>
                            {% else %}
                                <strong class="flow-text">
                                    <span class="discount">
                                        <sup>${{ product.price }}</sup>
                                    </span>
                                </strong>
                            {% endif %}
                    </div>
                </div>
            </div>
{#        </span>#}
{#    </div>#}
{#</div>#}

Captain_console/templates/checkout/shoppingcart_element.html
<div class="card-panel white">
    <div class="row">
        <div class="col s2">
            <a class="btn-floating btn-small waves-effect waves-light blue accent-3"><i class="material-icons">arrow_drop_up</i></a>
            <p><span id="quantity">{{ order_product.quantity }}</span></p>
            <a class="btn-floating btn-small waves-effect waves-light blue accent-3"><i class="material-icons">arrow_drop_down</i></a>
        </div>
        <div class="col s10">
{#            <h5 id="game-title">{{ order_product.id }}</h5>#}
            <h5 id="game-title">Mario</h5>

        </div>
    </div>
</div>