Captain_console/Captain_console/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('store/', include('store.urls')),
    path('login/', include('login.urls')),
    path('shoppingcart/', include('shoppingcart.urls')),
    path('checkout/', include('checkout.urls')),
    path('account/', include('account.urls')),
]

Captain_console/home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="home_index"),
    path('<int:id>', views.index_logout, name="home_index_logout")
]

Captain_console/store/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="store_index"),
    path('<int:id>', views.get_product_by_id, name="product_details"),
    path('search/<str:query>', views.search, name="search_page")
]

Captain_console/store/models.py
from django.db import models
from account.models import User

class Category(models.Model):
    name = models.CharField(max_length=64)

class Product(models.Model):
    name = models.CharField(max_length=128)
    price = models.FloatField()
    discount = models.FloatField(null=True)
    copies_sold = models.IntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    average_rating = models.FloatField(null=True)


    """
    Sets average rating of a product
    """
    def set_rating(self, rating, prod_id):
        Product.objects.filter(pk=prod_id).update(average_rating="{:.2f}".format(rating))

    """
    Returns average rating of a product
    """

    def get_rating(self):
        reviews = Review.objects.filter(product_id=self.id)

        total_ratings = 0
        for review in reviews:
            total_ratings += review.rating
        avg_rating = total_ratings / len(reviews)
        return avg_rating

    def __str__(self):
        return self.name

    """
        Returns the discounted price with two decimal numbers
    """

    def get_discounted_price(self):
        return "{:.2f}".format(self.price * 0.01 * (100 - self.discount))

    """
        Returns the total discount and removes any trailing zeros from float,
        ex. '50.0 => 50', and '13.5 => 13.5'
    """

    def get_discount(self):
        return "{:g}".format(self.discount)


class Genre(models.Model):
    genre = models.CharField(max_length=128)


class Developer(models.Model):
    developer = models.CharField(max_length=128)


class ProductDetails(models.Model):
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE)
    genre_id = models.ForeignKey(Genre, on_delete=models.CASCADE)
    developer_id = models.ForeignKey(Developer, on_delete=models.CASCADE)
    release_date = models.DateField()
    description = models.TextField()


class ProductPhoto(models.Model):
    path = models.CharField(max_length=999)
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE)
    alt = models.CharField(max_length=128, blank=True)

    def __str__(self):
        return self.path


class Review(models.Model):
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.IntegerField()
    comment = models.TextField(blank=True)

    def create_review(self, prod_id, user_id, rating):
        Review.objects.create(product_id=prod_id, user_id=user_id, rating=rating, comment="")

    def __str__(self):
        return str(self.rating)

Captain_console/store/views.py
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.views.decorators.csrf import csrf_exempt
from store.models import Product, ProductDetails, ProductPhoto, Review, Developer

from account.models import User
from checkout.models import OrderProduct
import json


def index(request):
    # Search
    if 'search_by' in request.GET:
        search_by = request.GET['search_by']
        products = Product.objects.filter(name__icontains=search_by)

        product_resp = [{
            'id': x.id
        } for x in products]
        return JsonResponse({'data': product_resp})

    # Sort by price, name or rating
    elif 'sort_by' in request.GET:
        sort_by = request.GET['sort_by']

        if sort_by == "price":
            products = Product.objects.all().order_by('price')
        elif sort_by == "name":
            products = Product.objects.all().order_by('name')
        elif sort_by == "rating":
            products = Product.objects.all().order_by('-average_rating')

        product_resp = [{
            'id': x.id,
            'name': x.name,
        } for x in products]
        return JsonResponse({'data': product_resp})

    # Filter applications
    elif 'filter_by' in request.GET:
        data = request.GET
        developer = data.get("developer")
        genre = data.get("genre")
        category = data.get("category")

        # Developer filter - get all products by filter
        if (developer == "All") or (developer == "Developer"):
            dev_products = Product.objects.all()
        else:
            dev_products = Product.objects.filter(productdetails__developer_id__developer__exact=developer)

        # Genre filter - get all products by filter
        if (genre == "All") or (genre == "Genre"):
            genre_products = Product.objects.all()
        else:
            genre_products = Product.objects.filter(productdetails__genre_id__genre__exact=genre)

        # Category filter - get all products by filter
        if (category == "All") or (category == "Category"):
            cat_products = Product.objects.all()
        else:
            cat_products = Product.objects.filter(category__name__exact=category)

        # Find the union of filtered items and return
        filtered_products = dev_products & genre_products & cat_products
        product_resp = [{
            'id': x.id,
        } for x in filtered_products]
        return JsonResponse({'data': product_resp})

    # Add to cart
    elif 'add_to_cart' in request.POST:
        data = request.POST
        user_id = request.session.get('user_id')
        order_product = OrderProduct()

    # Initial Store load - order by name
    context = {'products': Product.objects.all().order_by('name')}
    return render(request, 'store/index.html', context)


# Get product details
@csrf_exempt
def get_product_by_id(request, id):
    if 'copies_sold' in request.GET:
        copies_sold = OrderProduct.objects.filter(product_id=id).count()
        response = json.dumps({'status': 200, 'message': copies_sold})
        return HttpResponse(response, content_type='application/json')

    # Review product
    if 'review_product' in request.GET:
        data = request.POST
        prod_id = data.get("prod_id")
        rating = data.get("rating")
        user_id = request.session.get('user_id')
        user = User.objects.get(pk=user_id)

        # Get Product and User instances and create review
        product = get_object_or_404(Product, pk=prod_id)
        new_review = Review()
        new_review.create_review(product, user, rating)

        # Update average rating for the product
        new_rating = product.get_rating()
        product.set_rating(new_rating, prod_id)
        return redirect('product_details', id=id)

    return render(request, 'store/product_details.html', {
        'product': get_object_or_404(Product, pk=id)
    })


# Dynamic search in store
def search(request, query):
    return render(request, 'store/search.html', {
        'search_results': get_list_or_404(Product.objects.filter(name__icontains=query)),
        'search_query': query
    })

Captain_console/templates/store/consoles.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static "css/store.css" %}">
{% endblock %}

{% block content %}

<h1>Consoles</h1>
{% endblock %}

Captain_console/templates/store/games.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static "css/store.css" %}">
{% endblock %}

{% block content %}

<h1>Games</h1>
{% endblock %}

Captain_console/templates/store/index.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static "css/store.css" %}">
    <link rel="stylesheet" href="{% static 'css/shared/product-card-view.css' %}">
    <link rel="stylesheet" href="{% static 'css/shared/custom-breadcrumbs.css' %}">
{% endblock %}

{% block content %}

    <div class="row store-container">
        <ul class="crumbs">
            <li><a href="{% url "home_index" %}">Home</a></li>
            <li class="active"><a href="#">Store</a></li>
        </ul>
        <div class="col s12 m12 l2">    <!-- Filter and select-->
            <form class="col s12">
                <div class="row">
                    <div class="input-field col s12">
                        <input id="search_product" type="text" class="validate" />
                        <label for="search_product">Search product by name</label>
                    </div>
                     <div class="input-field col s12">
                        <select id="orderby">
                            <option value="" disabled="disabled" selected="selected">Order by</option>
                            <option value="1">Price</option>
                            <option value="3">Name</option>
                            <option value="3">Rating</option>
                        </select>
                    </div>
                    <div class="input-field col s12">
                        <select class="filterby" id="developer_filter" >
                            <option value="" disabled="disabled" selected="selected">Developer</option>
                            <option value="0">All</option>
                            <option value="1">Nintendo PTD</option>
                            <option value="2">Sony</option>
                            <option value="3">Sega</option>
                            <option value="4">Amiga</option>
                            <option value="5">Commadore 64</option>
                            <option value="6">Legacy Engineering</option>

                        </select>
                    </div>
                    <div class="input-field col s12">
                        <select class="filterby" id="genre_filter">
                            <option value="" disabled="disabled" selected="selected">Genre</option>
                            <option value="0">All</option>
                            <option value="1">First Person Shooter</option>
                            <option value="2">Adventure</option>
                            <option value="3">Arcade</option>
                            <option value="4">RPG</option>
                            <option value="5">Platform</option>
                        </select>
                    </div>
                 <div class="input-field col s12">
                        <select class="filterby" id="category_filter">
                            <option value="" disabled="disabled" selected="selected">Category</option>
                            <option value="0">All</option>
                            <option value="1">Games</option>
                            <option value="2">Console</option>
                            <option value="2">Other</option>
                        </select>
                    </div>
                </div>

            </form>
        </div>
        <div class="content col s10">  <!-- Products-->
        <div class="filter-message"></div>
            <div class="row all_products">
                {% for product in products %}
                    {% include 'store/single_product.html' with product=product%}
                {% endfor %}
            </div>
        </div>
    </div>

    {% block js %}
        <script src="{% static "js/store.js" %}"></script>
    {%endblock%}
{% endblock %}

Captain_console/templates/store/product_details.html
{% extends "base.html" %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static "css/product_details.css" %}">
    <link rel="stylesheet" href="{% static "css/shared/custom-breadcrumbs.css" %}">
{% endblock %}

{% block content %}
    <div class="row store">
        <ul class="crumbs">
            <li><a href="{% url "home_index" %}">Home</a></li>
            <li><a href="{% url "store_index" %}">Store</a></li>
            <li class="active"><a href="#">{{ product.name }}</a></li>
        </ul>
        <div class="card-panel white col s12">
            <div class="row">
                <div class="col s12 m6 l4">
                    <div class="product-image">
                        <img class="responsive-img" width="300ems" src="{{product.productphoto_set.first.path}}" alt="{{ product.productphoto_set.first.alt }}"/>
                        <div class="copies-sold">
                            <span id="copies-sold-nr"></span>
                            <span>copies sold</span>
                        </div>
                        <div id="stars" data-average="{{ product.average_rating}}" >
                            <button class="star" data-rate="1" data-prod="{{ product.id }}"><i class="material-icons">star</i></button>
                            <button class="star" data-rate="2" data-prod="{{ product.id }}" ><i class="material-icons">star</i></button>
                            <button class="star" data-rate="3" data-prod="{{ product.id }}"><i class="material-icons">star</i></button>
                            <button class="star" data-rate="4" data-prod="{{ product.id }}"><i class="material-icons">star</i></button>
                            <button class="star" data-rate="5" data-prod="{{ product.id }}"><i class="material-icons">star</i></button><span id="rating-count" data-current-count="{{ product.review_set.count }}">({{ product.review_set.count }})</span>
                        </div>
                    </div>
                </div>
                <div class="col s12 m6 l8">
                    <h4>{{ product.name }}</h4>
                    <span class="stock-text in-stock">In stock</span>
                    <h6>{{ product.productdetails_set.first.description }}</h6>
                    <h6><strong>Release date:</strong> {{ product.productdetails_set.first.release_date }}</h6>
                    <h6><strong>Developer: </strong>{{ product.productdetails_set.first.developer_id.developer }}</h6>
                    <h6><strong>Genre: </strong>{{ product.productdetails_set.first.genre_id.genre }} </h6>
                    <div>
                        <div id="product-price">
                            {% if product.discount > 0 %}
                                <span class="set-price">${{ product.get_discounted_price }}</span>
                                <sup class="normal-price">{{ product.price }}</sup>
                            {% else %}
                                <span class="set-price">${{ product.price }}</span>
                            {% endif %}
                        </div>
                        <a class="waves-effect waves-light btn blue accent-3 add-to-cart"><i class="material-icons left">shopping_cart</i>Add to cart</a>
                        {% if 'user_id' in request.session %}
                            <a class="waves-effect waves-light btn blue accent-3" data-prod="{{ product }}" id="give-review" >Rate product</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% block js %}
    <script src="{% static "js/store.js" %}"></script>
    <script src="{% static "js/product_details.js" %}"></script>
{%endblock%}

{% endblock %}

Captain_console/templates/store/search.html
{% extends "base.html" %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/shared/product-card-view.css' %}">
{% endblock %}

{% block content %}
    <div class="container">

        <h2 class="flow-text">
            {{ search_results|length }} Search results based on '{{ search_query }}'
        </h2>
        <div class="row">
            {% for product in search_results %}
                <div class="col s12 m6 l6 xl3">
                    {% include 'product-card-view.html' with product=product %}
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

Captain_console/templates/store/single_product.html
<div class="col s12 m6 l4 product-card" id="{{ product.id }}">
    {% include 'product-card-view.html' with product=product %}
</div>